project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Same Data, Different Stories: Comparing Visual Explanations in Machine Learning"
  author:
    - Yichao Wang (yw4324)
  repo-url: https://yichaowanggg.github.io/Final-Project-5293/
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results-linear.qmd
    - results-non-linear.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true
    


