# Conclusion

In our project, we investigated linear and non-linear modelling techniques in this study to forecast consumer purchase behavior by using a simulated e-commerce dataset. We first fitted a logistic regression model to establish a simple, interpretable linear model. Based on our result, this model offered a simple perspective on feature effects and also provide us some useful technique about the linear model. To further capture the complecity and latent pattern inside the interaction effects, we used a random forest classifier, which greatly increasing model flexibility and predictive performance. We evaluated and interpreted both models using techniques such as Partial Dependence Plots, Added Variable Plots (for linear model only), Permutation Importance(for ono-linear model), and LIME. These interpretability plots generate that the random forest model is more effective in uncovering non-linear behaviors, whereas the logistic regression is better at predicting the local approximation. 